### ISSUE TITLE
Feature: User can view game information.

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/PlayValorant#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view game information.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a landing page that the user can easily access game information, toggle link visibility, find important details in the footer, and switch to the landing page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/ajax-project/assets/66459527/e7849420-08d6-4d10-9d9e-cc299b9091f4)
![image](https://github.com/restropiajr/ajax-project/assets/66459527/b2ea5bbe-4b7c-4ebc-bfff-05809e655d0e)
![image](https://github.com/restropiajr/ajax-project/assets/66459527/1b887db8-ffde-4068-ad47-b94b332ba0e6)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a navbar that shows logo and toggler.
- [x] Create a collapsed view for links (agents, weapons, maps, skins).
- [x] Add an addEventListener to the toggler to listen for a 'click' in order to toggle the view for links.
- [x] Add an addEventListener to the valorant icon to listen for a 'click' in order to view landing page.
  - [x] Define a function called viewSwap that switches between views.
- [x] Create a header showing valorant title and subtitle.
- [x] Create a main section for dominate the battle that contains the information for the following:
  - [x] gif
  - [x] title
  - [x] information
- [x] Create a main section for precise gunplay that contains the information for the following:
  - [x] gif
  - [x] title
  - [x] information
- [x] Create a main section for unleash agent power that contains the information for the following:
  - [x] gif
  - [x] title
  - [x] information
- [x] Create scroll up button that when clicked it scrolls back to the top of the screen.
- [x] Create a footer showing the riot games logo, valorant logo, teen ESRB rating, and a notice for mock website.
- **Clean Up**
  - [x] Make sure that click targets are either `<a>` or `<button>` elements.
  - [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
