### ISSUE TITLE
Feature: User can view their favorite skins.

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/PlayValorant#16]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can view their favorite skins.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a favorites functionality that allows the user to easily favorite skins, delete skins, and view skins.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://github.com/restropiajr/PlayValorant/assets/66459527/0f228f46-4718-4914-9e13-d02e9dc8abc7)
![image](https://github.com/restropiajr/PlayValorant/assets/66459527/f24787f6-b49d-4a7b-947c-ffff8feb3060)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create a favorites page and add on the view "favorites-page" to the viewSwap function.
- [x] Create title and subtitle for favorites.
- [x] Create favorites toggler (open and solid) inside the skin container.
- [x] Create a function that will take the closest skin-container and save it into local storage.
- [x] Create a function that will take the favorites from the local storage to render and append the favorites inside the favorites page.
[x] Create a function that will delete favorite skins from the favorites page.
• Clean Up
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
