### ISSUE TITLE
Feature: User can click to view the details of agents. 

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/PlayValorant#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click to view the details of agents. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create an agents page that the user can easily access agent information and switch between the landing page and agents page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/ajax-project/assets/66459527/c53e5a35-fce2-4c51-a5ef-aae804b4ccf5)
![image](https://github.com/restropiajr/ajax-project/assets/66459527/ca8c8291-80cf-4e92-afb5-692baa09cf6e)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create an agents page and add on the view "agents-page" to the viewSwap function.
- [x] Execute the viewSwap function for the valorantData.view to show the last viewed page.
- [x] Create title and subtitle for agents page.
- [x] Create a prototype DOM tree in HTML that shows the structure of the agent information.
- [x] Create a set of CSS for the prototype DOM tree that matches the Figma wireframe.
- [x] Ensure that the prototype DOM tree and CSS works as intended.
- [x] Once confirmed the prototype DOM tree works, create an XMLHttpRequest to the Valorant API.
   - [x] Request the agents information
   - [x] Create the prototype DOM tree in main.js and use the agents information to create multiple DOM tree for each agent.
   - [x] Create an add event listener for "hover" actions to show and unshow ability descriptions.
   - [x] Ensure that the JavaScript DOM tree works with the CSS as intended.
- **Clean Up**
  - [x] Make sure that click targets are either <a> or <button> elements.
  - [x] Make sure that all click targets show a cursor: pointer when hovered with the mouse.
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
