### ISSUE TITLE
Feature: User can click to view the details of maps.

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/PlayValorant#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click to view the details of maps.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a maps page that the user can easily access map information and switch between the landing page, agents page., weapons page, and maps page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/ajax-project/assets/66459527/f85298bc-5650-48a2-8c32-13c8004efa15)
![image](https://github.com/restropiajr/ajax-project/assets/66459527/a75595fb-1a23-4487-9f0d-ab602cf75ded)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a maps page and add on the view "maps-page" to the viewSwap function. 
- [x] Create title and subtitle for maps page.
- [x] Create a prototype DOM tree in HTML that shows the structure of the map information.
- [x] Create a set of CSS for the prototype DOM tree that matches the Figma wireframe.
- [x] Ensure that the prototype DOM tree and CSS works as intended.
- [x] Once confirmed the prototype DOM tree works, create an XMLHttpRequest to the Valorant API.
   - [x] Request the map information
   - [x] Create the prototype DOM tree in main.js and use the maps information to create multiple DOM tree for each map.
   - [x]  Ensure that the JavaScript DOM tree works with the CSS as intended.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
