### ISSUE TITLE
Feature: User can click to search through different types of purchasable skins from the in-game shop.

### ISSUE THREAD

**Issue by restropiajr** [restropiajr/PlayValorant#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click to search through different types of purchasable skins from the in-game shop.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a skins page that the user can easily access skin information, switch between the landing page, agents page., weapons page, maps page and skins page, and search specific skins by weapon category or skin name.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/restropiajr/ajax-project/assets/66459527/639adc37-92a5-40d5-b693-8ec5deba77b1)
![image](https://github.com/restropiajr/ajax-project/assets/66459527/1fc35825-81ab-418a-9dcd-a0796f04340f)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a skins page and add on the view "skins-page" to the viewSwap function. 
- [x] Create title and subtitle for skinspage.
- [x] Create a prototype DOM tree in HTML that shows the structure of the skininformation.
- [x] Create a set of CSS for the prototype DOM tree that matches the Figma wireframe.
- [x] Ensure that the prototype DOM tree and CSS works as intended.
- [x] Once confirmed the prototype DOM tree works, create an XMLHttpRequest to the Valorant API.
   - [x] Request the skins information
   - [x] Create the prototype DOM tree in main.js and use the skins information to create multiple DOM tree for each skin.
   - [x]  Ensure that the JavaScript DOM tree works with the CSS as intended.
- [x] Create a function called searchSkin that takes filters through the data with the category of the weapon and name of the skin.
- [x] Create a search bar inside the HTML and use DOM query inside JavaScript to combine the HTML element and the function searchSkin.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
